apiVersion: v1
kind: Service
metadata:
  name: statement-fetcher-backend
spec:
  selector:
    app.kubernetes.io/name: statement-fetcher
    app.kubernetes.io/component: backend
  ports:
    - name: http
      protocol: TCP
      port: 8765
      targetPort: http
