apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: statement-fetcher
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: statement-fetcher.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: statement-fetcher
                port:
                  number: 80
